### ISSUE TITLE
Logging 2

### ISSUE THREAD

**Issue by ivankorobkov** [epochtimeout/baselibrary#9]
Logging:
- [x] Logging.
- [x] Text formatter.
- [x] Console writer.
- [x] File writer.
- [x] Config.
- [x] Null/stdout/stderr logger.
- [x] Stacks.

Usage:
```go
db.logger.Info("Created database snapshot",
	"index", index,
	"size", db.wal.size())

db.logger.Build().
	Level(Level).
	Info("Failed to create database snapshot").
	Infof("Failed to create database snapshot: %v", st).
	Msg("Hello, world").
	Msgf("Hello %v", name).
	Stack().
	Status(st).
	Fields("database", "snapshot", "index", index).
	Send()
```

Levels:
```
FATAL
ERROR
INFO
DEBUG
TRACE
```

Config:
```yaml
# default level
level: info

# default console logger
console:
  level: info

# default file logger
file:
  level: debug
  path: var/log/iqchanneld.log
  max_size: 256mb
  max_age: 7d
  max_backups: 16

# more levels
levels:
  shard: info
  shard.*: info
  shard.machine.*: warn
  shard.machine.engine: info
  shard.machine.storage: info
  shard.machine.database: trace
  shard.machine.storage: trace

# more file loggers
files:
  - path: var/log/error.log
    level: error

# syslog logger
syslog:
  host: localhost
  port: 1234
```
